# Generated by Django 3.1.2 on 2020-11-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201109_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='Select Category', on_delete=django.db.models.deletion.CASCADE, to='todo.category'),
        ),
    ]
